version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment: 
      # Obviously not a production-ready way to pass config info, but for experimenting. We don't want to copy the .env file into the image.
      - PORT=8000
      - DB_URL=mongodb://mongo:27017
      - DB_NAME=notes-api
      - DB_COLLECTION=notes
    links:
      - mongo 
    depends_on: 
      - mongo 
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # To persist data across container builds.
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles